name: BackupOnEvent
version: 1.6
author: Enayet Hussain (enayet123)
api-version: 1.15
main: BackupOnEvent
description: Backs up all worlds based on events
commands:
  backup:
    description: Force backup to happen immediately
    usage: /backup