name: BackupOnEvent
version: 1.6.4
author: Enayet Hussain (enayet123)
main: BackupOnEvent
description: Backs up all worlds based on events
commands:
  backup:
    description: Force backup to happen immediately
    usage: /backup